import jsPDF from 'jspdf'
import type { AgreementFormData, AgreementClause } from './agreementTemplate'
import { generateAgreementClauses } from './agreementTemplate'

/**
 * Generate a professional PDF for an Assured Tenancy Agreement.
 * Multi-page with headers, numbered clauses, and signature blocks.
 */

const TEAL = [15, 118, 110] as const // #0f766e
const SLATE_900 = [15, 23, 42] as const
const SLATE_600 = [71, 85, 105] as const
const SLATE_400 = [148, 163, 184] as const
const WHITE = [255, 255, 255] as const

const PAGE_WIDTH = 210
const PAGE_HEIGHT = 297
const MARGIN_LEFT = 25
const MARGIN_RIGHT = 25
const MARGIN_TOP = 25
const MARGIN_BOTTOM = 30
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT

function formatDateLong(dateStr: string): string {
  const d = new Date(dateStr)
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
}

export function generateAgreementPdf(
  data: AgreementFormData,
  landlordSignature?: { data: string; type: 'drawn' | 'typed'; date: string },
  tenantSignature?: { data: string; type: 'drawn' | 'typed'; date: string },
): jsPDF {
  const doc = new jsPDF('p', 'mm', 'a4')
  let y = MARGIN_TOP

  // ── Helpers ────────────────────────────────────────────────
  function checkPageBreak(needed: number) {
    if (y + needed > PAGE_HEIGHT - MARGIN_BOTTOM) {
      doc.addPage()
      y = MARGIN_TOP
      drawPageHeader()
    }
  }

  function drawPageHeader() {
    doc.setFillColor(...TEAL)
    doc.rect(0, 0, PAGE_WIDTH, 3, 'F')

    doc.setFontSize(7)
    doc.setTextColor(...SLATE_400)
    doc.setFont('helvetica', 'normal')
    doc.text('Written Statement of Terms — Assured Tenancy', MARGIN_LEFT, 10)
    doc.text(data.propertyAddress, PAGE_WIDTH - MARGIN_RIGHT, 10, { align: 'right' })

    // Thin line under header
    doc.setDrawColor(...SLATE_400)
    doc.setLineWidth(0.2)
    doc.line(MARGIN_LEFT, 14, PAGE_WIDTH - MARGIN_RIGHT, 14)

    y = 20
  }

  function drawFooter(pageNum: number, totalPages: number) {
    doc.setFontSize(7)
    doc.setTextColor(...SLATE_400)
    doc.setFont('helvetica', 'normal')
    doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_WIDTH / 2, PAGE_HEIGHT - 12, { align: 'center' })
    doc.text('Generated by Tenancy Portal', MARGIN_LEFT, PAGE_HEIGHT - 12)
  }

  // ── Title Page ─────────────────────────────────────────────

  // Teal header bar
  doc.setFillColor(...TEAL)
  doc.rect(0, 0, PAGE_WIDTH, 60, 'F')

  // Title text
  doc.setTextColor(...WHITE)
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text('Written Statement of Terms', MARGIN_LEFT, 30)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'normal')
  doc.text('for an Assured Tenancy', MARGIN_LEFT, 40)

  doc.setFontSize(9)
  doc.text('Under the Housing Act 1988 (as amended by the Renters\' Rights Act 2025)', MARGIN_LEFT, 52)

  y = 75

  // Summary box
  doc.setFillColor(248, 250, 252) // slate-50
  doc.roundedRect(MARGIN_LEFT, y, CONTENT_WIDTH, 68, 3, 3, 'F')

  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...TEAL)
  doc.text('PARTIES', MARGIN_LEFT + 8, y + 10)

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...SLATE_900)
  doc.text(`Landlord:   ${data.landlordName}`, MARGIN_LEFT + 8, y + 18)
  doc.text(`Tenant:       ${data.tenantName}`, MARGIN_LEFT + 8, y + 25)

  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...TEAL)
  doc.text('PROPERTY', MARGIN_LEFT + 8, y + 36)

  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...SLATE_900)
  doc.text(data.propertyAddress, MARGIN_LEFT + 8, y + 44)
  doc.text(data.propertyPostcode, MARGIN_LEFT + 8, y + 51)

  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...TEAL)
  doc.text('KEY TERMS', MARGIN_LEFT + CONTENT_WIDTH / 2, y + 36)

  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...SLATE_900)
  doc.text(`Rent: £${data.monthlyRent.toLocaleString('en-GB', { minimumFractionDigits: 2 })} pcm`, MARGIN_LEFT + CONTENT_WIDTH / 2, y + 44)
  doc.text(`Start: ${formatDateLong(data.startDate)}`, MARGIN_LEFT + CONTENT_WIDTH / 2, y + 51)
  doc.text(`Deposit: £${data.depositAmount.toLocaleString('en-GB', { minimumFractionDigits: 2 })}`, MARGIN_LEFT + CONTENT_WIDTH / 2, y + 58)

  y += 80

  // Important notice
  doc.setFillColor(254, 252, 232) // amber-50
  doc.roundedRect(MARGIN_LEFT, y, CONTENT_WIDTH, 20, 2, 2, 'F')
  doc.setDrawColor(251, 191, 36) // amber-400
  doc.setLineWidth(0.3)
  doc.roundedRect(MARGIN_LEFT, y, CONTENT_WIDTH, 20, 2, 2, 'S')

  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(146, 64, 14) // amber-800
  doc.text('IMPORTANT', MARGIN_LEFT + 8, y + 7)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7.5)
  doc.text('This is a Written Statement of Terms as required by the Renters\' Rights Act 2025.', MARGIN_LEFT + 8, y + 13)
  doc.text('Both parties should read and understand all terms before signing.', MARGIN_LEFT + 8, y + 18)

  // ── Clauses Pages ──────────────────────────────────────────

  const clauses = generateAgreementClauses(data)

  doc.addPage()
  y = MARGIN_TOP
  drawPageHeader()

  for (const clause of clauses) {
    // Clause header needs ~15mm, check
    checkPageBreak(20)

    // Clause number + title
    doc.setFillColor(...TEAL)
    doc.roundedRect(MARGIN_LEFT, y, 8, 8, 1.5, 1.5, 'F')
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...WHITE)
    doc.text(clause.number, MARGIN_LEFT + 4, y + 5.8, { align: 'center' })

    doc.setTextColor(...SLATE_900)
    doc.setFontSize(11)
    doc.text(clause.title, MARGIN_LEFT + 12, y + 5.8)

    // Underline
    doc.setDrawColor(...SLATE_400)
    doc.setLineWidth(0.15)
    doc.line(MARGIN_LEFT, y + 10, PAGE_WIDTH - MARGIN_RIGHT, y + 10)

    y += 15

    // Clause intro text
    if (clause.text) {
      checkPageBreak(8)
      doc.setFontSize(9)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...SLATE_600)
      const introLines = doc.splitTextToSize(clause.text, CONTENT_WIDTH - 5)
      doc.text(introLines, MARGIN_LEFT + 5, y)
      y += introLines.length * 4.2 + 2
    }

    // Subclauses
    if (clause.subclauses) {
      for (let i = 0; i < clause.subclauses.length; i++) {
        const subText = clause.subclauses[i]
        doc.setFontSize(8.5)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(...SLATE_900)

        const wrappedLines = doc.splitTextToSize(subText, CONTENT_WIDTH - 18)
        const blockHeight = wrappedLines.length * 3.8 + 3

        checkPageBreak(blockHeight)

        // Subclause number
        doc.setTextColor(...TEAL)
        doc.setFont('helvetica', 'bold')
        doc.text(`${clause.number}.${i + 1}`, MARGIN_LEFT + 5, y)

        // Subclause text
        doc.setTextColor(...SLATE_900)
        doc.setFont('helvetica', 'normal')
        doc.text(wrappedLines, MARGIN_LEFT + 18, y)

        y += blockHeight
      }
    }

    y += 6 // Space between clauses
  }

  // ── Signature Page ─────────────────────────────────────────

  checkPageBreak(100)

  // If we're close to bottom, start a new page for signatures
  if (y > PAGE_HEIGHT - MARGIN_BOTTOM - 100) {
    doc.addPage()
    y = MARGIN_TOP
    drawPageHeader()
  }

  // Signature section header
  doc.setFillColor(...TEAL)
  doc.rect(MARGIN_LEFT, y, CONTENT_WIDTH, 10, 'F')
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...WHITE)
  doc.text('SIGNATURES', MARGIN_LEFT + 5, y + 7)
  y += 18

  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...SLATE_600)
  doc.text(
    'By signing below, both parties confirm they have read, understood, and agree to the terms of this Agreement.',
    MARGIN_LEFT,
    y,
  )
  y += 10

  // ── Landlord Signature Block ─────
  doc.setFillColor(248, 250, 252)
  doc.roundedRect(MARGIN_LEFT, y, CONTENT_WIDTH, 40, 2, 2, 'F')

  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...TEAL)
  doc.text('LANDLORD', MARGIN_LEFT + 5, y + 7)

  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...SLATE_900)
  doc.setFontSize(9)
  doc.text(`Name: ${data.landlordName}`, MARGIN_LEFT + 5, y + 15)

  if (landlordSignature) {
    if (landlordSignature.type === 'drawn' && landlordSignature.data.startsWith('data:image')) {
      try {
        doc.addImage(landlordSignature.data, 'PNG', MARGIN_LEFT + 5, y + 18, 50, 15)
      } catch {
        doc.setFont('helvetica', 'italic')
        doc.text('[Signature on file]', MARGIN_LEFT + 5, y + 28)
      }
    } else {
      doc.setFontSize(16)
      doc.setFont('helvetica', 'italic')
      doc.setTextColor(...SLATE_900)
      doc.text(landlordSignature.data, MARGIN_LEFT + 5, y + 30)
    }
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...SLATE_600)
    doc.text(`Signed: ${formatDateLong(landlordSignature.date)}`, MARGIN_LEFT + CONTENT_WIDTH / 2 + 10, y + 15)
  } else {
    doc.setDrawColor(...SLATE_400)
    doc.setLineWidth(0.2)
    doc.line(MARGIN_LEFT + 45, y + 32, MARGIN_LEFT + CONTENT_WIDTH / 2 - 5, y + 32)
    doc.setFontSize(7)
    doc.setTextColor(...SLATE_400)
    doc.text('Signature', MARGIN_LEFT + 45, y + 36)

    doc.line(MARGIN_LEFT + CONTENT_WIDTH / 2 + 10, y + 32, PAGE_WIDTH - MARGIN_RIGHT - 5, y + 32)
    doc.text('Date', MARGIN_LEFT + CONTENT_WIDTH / 2 + 10, y + 36)
  }

  y += 48

  // ── Tenant Signature Block ─────
  doc.setFillColor(248, 250, 252)
  doc.roundedRect(MARGIN_LEFT, y, CONTENT_WIDTH, 40, 2, 2, 'F')

  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...TEAL)
  doc.text('TENANT', MARGIN_LEFT + 5, y + 7)

  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...SLATE_900)
  doc.setFontSize(9)
  doc.text(`Name: ${data.tenantName}`, MARGIN_LEFT + 5, y + 15)

  if (tenantSignature) {
    if (tenantSignature.type === 'drawn' && tenantSignature.data.startsWith('data:image')) {
      try {
        doc.addImage(tenantSignature.data, 'PNG', MARGIN_LEFT + 5, y + 18, 50, 15)
      } catch {
        doc.setFont('helvetica', 'italic')
        doc.text('[Signature on file]', MARGIN_LEFT + 5, y + 28)
      }
    } else {
      doc.setFontSize(16)
      doc.setFont('helvetica', 'italic')
      doc.setTextColor(...SLATE_900)
      doc.text(tenantSignature.data, MARGIN_LEFT + 5, y + 30)
    }
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...SLATE_600)
    doc.text(`Signed: ${formatDateLong(tenantSignature.date)}`, MARGIN_LEFT + CONTENT_WIDTH / 2 + 10, y + 15)
  } else {
    doc.setDrawColor(...SLATE_400)
    doc.setLineWidth(0.2)
    doc.line(MARGIN_LEFT + 45, y + 32, MARGIN_LEFT + CONTENT_WIDTH / 2 - 5, y + 32)
    doc.setFontSize(7)
    doc.setTextColor(...SLATE_400)
    doc.text('Signature', MARGIN_LEFT + 45, y + 36)

    doc.line(MARGIN_LEFT + CONTENT_WIDTH / 2 + 10, y + 32, PAGE_WIDTH - MARGIN_RIGHT - 5, y + 32)
    doc.text('Date', MARGIN_LEFT + CONTENT_WIDTH / 2 + 10, y + 36)
  }

  // ── Page Numbers ───────────────────────────────────────────

  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    drawFooter(i, totalPages)
  }

  return doc
}

/**
 * Generate and download the PDF
 */
export function downloadAgreementPdf(
  data: AgreementFormData,
  landlordSignature?: { data: string; type: 'drawn' | 'typed'; date: string },
  tenantSignature?: { data: string; type: 'drawn' | 'typed'; date: string },
) {
  const doc = generateAgreementPdf(data, landlordSignature, tenantSignature)
  const filename = `Tenancy_Agreement_${data.propertyPostcode.replace(/\s+/g, '_')}_${data.tenantName.replace(/\s+/g, '_')}.pdf`
  doc.save(filename)
}

/**
 * Generate PDF as blob for upload to Supabase storage
 */
export function generateAgreementPdfBlob(
  data: AgreementFormData,
  landlordSignature?: { data: string; type: 'drawn' | 'typed'; date: string },
  tenantSignature?: { data: string; type: 'drawn' | 'typed'; date: string },
): Blob {
  const doc = generateAgreementPdf(data, landlordSignature, tenantSignature)
  return doc.output('blob')
}
